/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgOrgSlugRouteImport } from './routes/org/$orgSlug'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCreateOrganizationRouteImport } from './routes/auth/create-organization'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as OrgOrgSlugIndexRouteImport } from './routes/org/$orgSlug/index'
import { Route as OrgOrgSlugProjectsRouteImport } from './routes/org/$orgSlug/projects'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as OrgOrgSlugTasksIndexRouteImport } from './routes/org/$orgSlug/tasks.index'
import { Route as OrgOrgSlugProjectsIndexRouteImport } from './routes/org/$orgSlug/projects.index'
import { Route as OrgOrgSlugTeamTeamSlugRouteImport } from './routes/org/$orgSlug/team.$teamSlug'
import { Route as OrgOrgSlugTeamTeamSlugTasksRouteImport } from './routes/org/$orgSlug/team.$teamSlug.tasks'
import { Route as OrgOrgSlugTeamTeamSlugProjectsRouteImport } from './routes/org/$orgSlug/team.$teamSlug.projects'
import { Route as OrgOrgSlugProjectsProjectIdTasksRouteImport } from './routes/org/$orgSlug/projects.$projectId.tasks'
import { Route as OrgOrgSlugTeamTeamSlugProjectsIndexRouteImport } from './routes/org/$orgSlug/team.$teamSlug.projects.index'
import { Route as OrgOrgSlugTeamTeamSlugProjectsProjectIdTasksRouteImport } from './routes/org/$orgSlug/team.$teamSlug.projects.$projectId.tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgSlugRoute = OrgOrgSlugRouteImport.update({
  id: '/org/$orgSlug',
  path: '/org/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreateOrganizationRoute = AuthCreateOrganizationRouteImport.update({
  id: '/auth/create-organization',
  path: '/auth/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgSlugIndexRoute = OrgOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgSlugRoute,
} as any)
const OrgOrgSlugProjectsRoute = OrgOrgSlugProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => OrgOrgSlugRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgSlugTasksIndexRoute = OrgOrgSlugTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => OrgOrgSlugRoute,
} as any)
const OrgOrgSlugProjectsIndexRoute = OrgOrgSlugProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgSlugProjectsRoute,
} as any)
const OrgOrgSlugTeamTeamSlugRoute = OrgOrgSlugTeamTeamSlugRouteImport.update({
  id: '/team/$teamSlug',
  path: '/team/$teamSlug',
  getParentRoute: () => OrgOrgSlugRoute,
} as any)
const OrgOrgSlugTeamTeamSlugTasksRoute =
  OrgOrgSlugTeamTeamSlugTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => OrgOrgSlugTeamTeamSlugRoute,
  } as any)
const OrgOrgSlugTeamTeamSlugProjectsRoute =
  OrgOrgSlugTeamTeamSlugProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => OrgOrgSlugTeamTeamSlugRoute,
  } as any)
const OrgOrgSlugProjectsProjectIdTasksRoute =
  OrgOrgSlugProjectsProjectIdTasksRouteImport.update({
    id: '/$projectId/tasks',
    path: '/$projectId/tasks',
    getParentRoute: () => OrgOrgSlugProjectsRoute,
  } as any)
const OrgOrgSlugTeamTeamSlugProjectsIndexRoute =
  OrgOrgSlugTeamTeamSlugProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgOrgSlugTeamTeamSlugProjectsRoute,
  } as any)
const OrgOrgSlugTeamTeamSlugProjectsProjectIdTasksRoute =
  OrgOrgSlugTeamTeamSlugProjectsProjectIdTasksRouteImport.update({
    id: '/$projectId/tasks',
    path: '/$projectId/tasks',
    getParentRoute: () => OrgOrgSlugTeamTeamSlugProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/create-organization': typeof AuthCreateOrganizationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/org/$orgSlug': typeof OrgOrgSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/org/$orgSlug/projects': typeof OrgOrgSlugProjectsRouteWithChildren
  '/org/$orgSlug/': typeof OrgOrgSlugIndexRoute
  '/org/$orgSlug/team/$teamSlug': typeof OrgOrgSlugTeamTeamSlugRouteWithChildren
  '/org/$orgSlug/projects/': typeof OrgOrgSlugProjectsIndexRoute
  '/org/$orgSlug/tasks/': typeof OrgOrgSlugTasksIndexRoute
  '/org/$orgSlug/projects/$projectId/tasks': typeof OrgOrgSlugProjectsProjectIdTasksRoute
  '/org/$orgSlug/team/$teamSlug/projects': typeof OrgOrgSlugTeamTeamSlugProjectsRouteWithChildren
  '/org/$orgSlug/team/$teamSlug/tasks': typeof OrgOrgSlugTeamTeamSlugTasksRoute
  '/org/$orgSlug/team/$teamSlug/projects/': typeof OrgOrgSlugTeamTeamSlugProjectsIndexRoute
  '/org/$orgSlug/team/$teamSlug/projects/$projectId/tasks': typeof OrgOrgSlugTeamTeamSlugProjectsProjectIdTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/create-organization': typeof AuthCreateOrganizationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/org/$orgSlug': typeof OrgOrgSlugIndexRoute
  '/org/$orgSlug/team/$teamSlug': typeof OrgOrgSlugTeamTeamSlugRouteWithChildren
  '/org/$orgSlug/projects': typeof OrgOrgSlugProjectsIndexRoute
  '/org/$orgSlug/tasks': typeof OrgOrgSlugTasksIndexRoute
  '/org/$orgSlug/projects/$projectId/tasks': typeof OrgOrgSlugProjectsProjectIdTasksRoute
  '/org/$orgSlug/team/$teamSlug/tasks': typeof OrgOrgSlugTeamTeamSlugTasksRoute
  '/org/$orgSlug/team/$teamSlug/projects': typeof OrgOrgSlugTeamTeamSlugProjectsIndexRoute
  '/org/$orgSlug/team/$teamSlug/projects/$projectId/tasks': typeof OrgOrgSlugTeamTeamSlugProjectsProjectIdTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/create-organization': typeof AuthCreateOrganizationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/org/$orgSlug': typeof OrgOrgSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/org/$orgSlug/projects': typeof OrgOrgSlugProjectsRouteWithChildren
  '/org/$orgSlug/': typeof OrgOrgSlugIndexRoute
  '/org/$orgSlug/team/$teamSlug': typeof OrgOrgSlugTeamTeamSlugRouteWithChildren
  '/org/$orgSlug/projects/': typeof OrgOrgSlugProjectsIndexRoute
  '/org/$orgSlug/tasks/': typeof OrgOrgSlugTasksIndexRoute
  '/org/$orgSlug/projects/$projectId/tasks': typeof OrgOrgSlugProjectsProjectIdTasksRoute
  '/org/$orgSlug/team/$teamSlug/projects': typeof OrgOrgSlugTeamTeamSlugProjectsRouteWithChildren
  '/org/$orgSlug/team/$teamSlug/tasks': typeof OrgOrgSlugTeamTeamSlugTasksRoute
  '/org/$orgSlug/team/$teamSlug/projects/': typeof OrgOrgSlugTeamTeamSlugProjectsIndexRoute
  '/org/$orgSlug/team/$teamSlug/projects/$projectId/tasks': typeof OrgOrgSlugTeamTeamSlugProjectsProjectIdTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/auth/create-organization'
    | '/auth/login'
    | '/auth/signup'
    | '/org/$orgSlug'
    | '/api/auth/$'
    | '/org/$orgSlug/projects'
    | '/org/$orgSlug/'
    | '/org/$orgSlug/team/$teamSlug'
    | '/org/$orgSlug/projects/'
    | '/org/$orgSlug/tasks/'
    | '/org/$orgSlug/projects/$projectId/tasks'
    | '/org/$orgSlug/team/$teamSlug/projects'
    | '/org/$orgSlug/team/$teamSlug/tasks'
    | '/org/$orgSlug/team/$teamSlug/projects/'
    | '/org/$orgSlug/team/$teamSlug/projects/$projectId/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/auth/create-organization'
    | '/auth/login'
    | '/auth/signup'
    | '/api/auth/$'
    | '/org/$orgSlug'
    | '/org/$orgSlug/team/$teamSlug'
    | '/org/$orgSlug/projects'
    | '/org/$orgSlug/tasks'
    | '/org/$orgSlug/projects/$projectId/tasks'
    | '/org/$orgSlug/team/$teamSlug/tasks'
    | '/org/$orgSlug/team/$teamSlug/projects'
    | '/org/$orgSlug/team/$teamSlug/projects/$projectId/tasks'
  id:
    | '__root__'
    | '/'
    | '/api/$'
    | '/auth/create-organization'
    | '/auth/login'
    | '/auth/signup'
    | '/org/$orgSlug'
    | '/api/auth/$'
    | '/org/$orgSlug/projects'
    | '/org/$orgSlug/'
    | '/org/$orgSlug/team/$teamSlug'
    | '/org/$orgSlug/projects/'
    | '/org/$orgSlug/tasks/'
    | '/org/$orgSlug/projects/$projectId/tasks'
    | '/org/$orgSlug/team/$teamSlug/projects'
    | '/org/$orgSlug/team/$teamSlug/tasks'
    | '/org/$orgSlug/team/$teamSlug/projects/'
    | '/org/$orgSlug/team/$teamSlug/projects/$projectId/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthCreateOrganizationRoute: typeof AuthCreateOrganizationRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  OrgOrgSlugRoute: typeof OrgOrgSlugRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgSlug': {
      id: '/org/$orgSlug'
      path: '/org/$orgSlug'
      fullPath: '/org/$orgSlug'
      preLoaderRoute: typeof OrgOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/create-organization': {
      id: '/auth/create-organization'
      path: '/auth/create-organization'
      fullPath: '/auth/create-organization'
      preLoaderRoute: typeof AuthCreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgSlug/': {
      id: '/org/$orgSlug/'
      path: '/'
      fullPath: '/org/$orgSlug/'
      preLoaderRoute: typeof OrgOrgSlugIndexRouteImport
      parentRoute: typeof OrgOrgSlugRoute
    }
    '/org/$orgSlug/projects': {
      id: '/org/$orgSlug/projects'
      path: '/projects'
      fullPath: '/org/$orgSlug/projects'
      preLoaderRoute: typeof OrgOrgSlugProjectsRouteImport
      parentRoute: typeof OrgOrgSlugRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgSlug/tasks/': {
      id: '/org/$orgSlug/tasks/'
      path: '/tasks'
      fullPath: '/org/$orgSlug/tasks/'
      preLoaderRoute: typeof OrgOrgSlugTasksIndexRouteImport
      parentRoute: typeof OrgOrgSlugRoute
    }
    '/org/$orgSlug/projects/': {
      id: '/org/$orgSlug/projects/'
      path: '/'
      fullPath: '/org/$orgSlug/projects/'
      preLoaderRoute: typeof OrgOrgSlugProjectsIndexRouteImport
      parentRoute: typeof OrgOrgSlugProjectsRoute
    }
    '/org/$orgSlug/team/$teamSlug': {
      id: '/org/$orgSlug/team/$teamSlug'
      path: '/team/$teamSlug'
      fullPath: '/org/$orgSlug/team/$teamSlug'
      preLoaderRoute: typeof OrgOrgSlugTeamTeamSlugRouteImport
      parentRoute: typeof OrgOrgSlugRoute
    }
    '/org/$orgSlug/team/$teamSlug/tasks': {
      id: '/org/$orgSlug/team/$teamSlug/tasks'
      path: '/tasks'
      fullPath: '/org/$orgSlug/team/$teamSlug/tasks'
      preLoaderRoute: typeof OrgOrgSlugTeamTeamSlugTasksRouteImport
      parentRoute: typeof OrgOrgSlugTeamTeamSlugRoute
    }
    '/org/$orgSlug/team/$teamSlug/projects': {
      id: '/org/$orgSlug/team/$teamSlug/projects'
      path: '/projects'
      fullPath: '/org/$orgSlug/team/$teamSlug/projects'
      preLoaderRoute: typeof OrgOrgSlugTeamTeamSlugProjectsRouteImport
      parentRoute: typeof OrgOrgSlugTeamTeamSlugRoute
    }
    '/org/$orgSlug/projects/$projectId/tasks': {
      id: '/org/$orgSlug/projects/$projectId/tasks'
      path: '/$projectId/tasks'
      fullPath: '/org/$orgSlug/projects/$projectId/tasks'
      preLoaderRoute: typeof OrgOrgSlugProjectsProjectIdTasksRouteImport
      parentRoute: typeof OrgOrgSlugProjectsRoute
    }
    '/org/$orgSlug/team/$teamSlug/projects/': {
      id: '/org/$orgSlug/team/$teamSlug/projects/'
      path: '/'
      fullPath: '/org/$orgSlug/team/$teamSlug/projects/'
      preLoaderRoute: typeof OrgOrgSlugTeamTeamSlugProjectsIndexRouteImport
      parentRoute: typeof OrgOrgSlugTeamTeamSlugProjectsRoute
    }
    '/org/$orgSlug/team/$teamSlug/projects/$projectId/tasks': {
      id: '/org/$orgSlug/team/$teamSlug/projects/$projectId/tasks'
      path: '/$projectId/tasks'
      fullPath: '/org/$orgSlug/team/$teamSlug/projects/$projectId/tasks'
      preLoaderRoute: typeof OrgOrgSlugTeamTeamSlugProjectsProjectIdTasksRouteImport
      parentRoute: typeof OrgOrgSlugTeamTeamSlugProjectsRoute
    }
  }
}

interface OrgOrgSlugProjectsRouteChildren {
  OrgOrgSlugProjectsIndexRoute: typeof OrgOrgSlugProjectsIndexRoute
  OrgOrgSlugProjectsProjectIdTasksRoute: typeof OrgOrgSlugProjectsProjectIdTasksRoute
}

const OrgOrgSlugProjectsRouteChildren: OrgOrgSlugProjectsRouteChildren = {
  OrgOrgSlugProjectsIndexRoute: OrgOrgSlugProjectsIndexRoute,
  OrgOrgSlugProjectsProjectIdTasksRoute: OrgOrgSlugProjectsProjectIdTasksRoute,
}

const OrgOrgSlugProjectsRouteWithChildren =
  OrgOrgSlugProjectsRoute._addFileChildren(OrgOrgSlugProjectsRouteChildren)

interface OrgOrgSlugTeamTeamSlugProjectsRouteChildren {
  OrgOrgSlugTeamTeamSlugProjectsIndexRoute: typeof OrgOrgSlugTeamTeamSlugProjectsIndexRoute
  OrgOrgSlugTeamTeamSlugProjectsProjectIdTasksRoute: typeof OrgOrgSlugTeamTeamSlugProjectsProjectIdTasksRoute
}

const OrgOrgSlugTeamTeamSlugProjectsRouteChildren: OrgOrgSlugTeamTeamSlugProjectsRouteChildren =
  {
    OrgOrgSlugTeamTeamSlugProjectsIndexRoute:
      OrgOrgSlugTeamTeamSlugProjectsIndexRoute,
    OrgOrgSlugTeamTeamSlugProjectsProjectIdTasksRoute:
      OrgOrgSlugTeamTeamSlugProjectsProjectIdTasksRoute,
  }

const OrgOrgSlugTeamTeamSlugProjectsRouteWithChildren =
  OrgOrgSlugTeamTeamSlugProjectsRoute._addFileChildren(
    OrgOrgSlugTeamTeamSlugProjectsRouteChildren,
  )

interface OrgOrgSlugTeamTeamSlugRouteChildren {
  OrgOrgSlugTeamTeamSlugProjectsRoute: typeof OrgOrgSlugTeamTeamSlugProjectsRouteWithChildren
  OrgOrgSlugTeamTeamSlugTasksRoute: typeof OrgOrgSlugTeamTeamSlugTasksRoute
}

const OrgOrgSlugTeamTeamSlugRouteChildren: OrgOrgSlugTeamTeamSlugRouteChildren =
  {
    OrgOrgSlugTeamTeamSlugProjectsRoute:
      OrgOrgSlugTeamTeamSlugProjectsRouteWithChildren,
    OrgOrgSlugTeamTeamSlugTasksRoute: OrgOrgSlugTeamTeamSlugTasksRoute,
  }

const OrgOrgSlugTeamTeamSlugRouteWithChildren =
  OrgOrgSlugTeamTeamSlugRoute._addFileChildren(
    OrgOrgSlugTeamTeamSlugRouteChildren,
  )

interface OrgOrgSlugRouteChildren {
  OrgOrgSlugProjectsRoute: typeof OrgOrgSlugProjectsRouteWithChildren
  OrgOrgSlugIndexRoute: typeof OrgOrgSlugIndexRoute
  OrgOrgSlugTeamTeamSlugRoute: typeof OrgOrgSlugTeamTeamSlugRouteWithChildren
  OrgOrgSlugTasksIndexRoute: typeof OrgOrgSlugTasksIndexRoute
}

const OrgOrgSlugRouteChildren: OrgOrgSlugRouteChildren = {
  OrgOrgSlugProjectsRoute: OrgOrgSlugProjectsRouteWithChildren,
  OrgOrgSlugIndexRoute: OrgOrgSlugIndexRoute,
  OrgOrgSlugTeamTeamSlugRoute: OrgOrgSlugTeamTeamSlugRouteWithChildren,
  OrgOrgSlugTasksIndexRoute: OrgOrgSlugTasksIndexRoute,
}

const OrgOrgSlugRouteWithChildren = OrgOrgSlugRoute._addFileChildren(
  OrgOrgSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthCreateOrganizationRoute: AuthCreateOrganizationRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  OrgOrgSlugRoute: OrgOrgSlugRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
